class Pessoa { //Especificar todos os obejtos pessoas (Abstração)

    //ATRIBUTOS
    nome
    idade
    altura 
    peso
    sexo




    //COMPORTAMENTOS

}

// Criar objetos do tipo Pessoa
 
//nossa variável
let p1 = new Pessoa()
p1.nome = 'Emanuel'
p1.idade = 22
p1.altura = 1.74
p1.sexo = 'Masculino'
console.log(` o nome é ${p1.nome} e tem ${p1.idade} anos`)


//--------------------------------------------------------------

let p2 = new Pessoa()
p2.nome = 'Mariana'
p2.idade = 16
p2.altura = 1.68
p2.sexo = 'Feminino'
console.log(` o nome é ${p2.nome} e tem ${p2.idade} anos`)
